name: deploying Hexo project to GitHub pages
on:
  push:
    branches:
      - master # master 分支有 push 行为时就触发这个 action

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Prepare ssh env
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_DEPLOY_KEY" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 'github.com' >> ~/.ssh/known_hosts          
        env:
          SSH_DEPLOY_KEY: ${{ secrets.HEXO_BLOG }}
      - name: Prepare hexo and npm env
        run: |
          npm install -g hexo-cli
          npm install          
      - name: Prepare git env
        run: |
          git config --global user.email huguobo2010@126.com
          git config --global user.name huguobo          
      - name: Deploy Blog
        run: | 
          hexo clean
          hexo g
          hexo d